name: EX Emulators - GBA Only

on: [push, pull_request]

jobs:
  build:
    name: Build base
    runs-on: ubuntu-latest
    steps:
    - name: Checkout emu-ex-plus-alpha repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Decode debug keystore
      env:
        DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
      run: |
        if [ -z "$DEBUG_KEYSTORE" ]
        then
          echo 'No debug keystore value'
        else
          echo "$DEBUG_KEYSTORE" | base64 --decode > .debug.keystore
          mkdir -p ~/.android
          mv .debug.keystore ~/.android/debug.keystore
        fi
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends autoconf automake autopoint bash gcc-arm-linux-gnueabi file gawk gettext git libtool libtool-bin make nasm pkg-config unzip wget
    - name: Install Latest CMake
      uses: lukka/get-cmake@latest
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Set up environment
      run: |
        mkdir imagine-sdk
        NDK_VERSION='r30-beta1'
        wget "https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux.zip"
        unzip android-ndk-${NDK_VERSION}-linux.zip
        rm android-ndk-${NDK_VERSION}-linux.zip
        mv android-ndk-${NDK_VERSION} android-ndk
        GITHUB_ENV_FILE=env.github
        echo "ANDROID_NDK_PATH=${{ github.workspace }}/android-ndk" >> "$GITHUB_ENV_FILE"
        echo "EMUFRAMEWORK_PATH=${{ github.workspace }}/EmuFramework" >> "$GITHUB_ENV_FILE"
        echo "IMAGINE_PATH=${{ github.workspace }}/imagine" >> "$GITHUB_ENV_FILE"
        echo "IMAGINE_SDK_PATH=${{ github.workspace }}/imagine-sdk" >> "$GITHUB_ENV_FILE"
        echo "COMMIT_PREFIX=$(echo ${{ github.sha }} | cut -c1-8)" >> "$GITHUB_ENV_FILE"
        cat "$GITHUB_ENV_FILE" >> $GITHUB_ENV
    - name: Run script
      working-directory: imagine/bundle/all
      run: |
        ./makeAll-android.sh install
      shell: bash
    - name: Build environment
      run: |
        $IMAGINE_PATH/android.sh config
        $IMAGINE_PATH/android.sh installLinks --config Release
        $EMUFRAMEWORK_PATH/android.sh config
        $EMUFRAMEWORK_PATH/android.sh installLinks --config Release
    - name: Keep cache small
      run: rm -rf .git
    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: ./
        key: ${{ github.sha }}-base

  build_gba:
    name: Build GBA.emu
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends autoconf automake autopoint bash gcc-arm-linux-gnueabi file gawk gettext git libtool libtool-bin make nasm pkg-config unzip wget
    - name: Install Latest CMake
      uses: lukka/get-cmake@latest
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: ./
        key: ${{ github.sha }}-base
        fail-on-cache-miss: true
    - name: Set up environment
      run: |
        GITHUB_ENV_FILE=env.github
        cat "$GITHUB_ENV_FILE" >> $GITHUB_ENV
    - name: Create EX-Emulators directory
      run: mkdir EX-Emulators
    - name: Build GBA.emu
      working-directory: GBA.emu
      run: |
        make -f android.mk android-apk CONFIG=Release V=1 -j`nproc`
        cp build/android/build/outputs/apk/release/GbaEmu-release.apk "../EX-Emulators/GbaEmu-${COMMIT_PREFIX}.apk"
    - name: Upload GBA artifact
      uses: actions/upload-artifact@v4
      with:
        name: GBA.emu
        path: EX-Emulators/

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build_gba]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout emu-ex-plus-alpha repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: EX-Emulators
        merge-multiple: true
    - name: Re-ZIP artifacts
      working-directory: EX-Emulators
      run: |
        mkdir ../dist
        COMMIT_PREFIX=$(echo ${{ github.sha }} | cut -c1-8)
        for artifact in *.apk
        do
          file_name="${artifact%.apk}"
          zip "../dist/${file_name//-${COMMIT_PREFIX}/}.zip" "${file_name}.apk"
        done
    - name: Update Git Tag
      run: |
        git tag -f Pre-release
        git push -f origin Pre-release
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        prerelease: true
        allowUpdates: true
        removeArtifacts: true
        tag: Pre-release
        artifacts: "dist/*.zip"
